#!/usr/bin/env python3
"""Static anti-circularity checks for the v0.4-aware artifact plan."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

PLAN_SCHEMA = "na-cu001-integration-closure-v0.3"


def fail(message: str) -> None:
    raise SystemExit(f"HOLD: {message}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", required=True)
    parser.add_argument("--stage-script", required=True)
    args = parser.parse_args()
    plan_path = Path(args.plan)
    script_path = Path(args.stage_script)
    plan = json.loads(plan_path.read_text())
    script = script_path.read_text()
    if plan.get("schema") != PLAN_SCHEMA:
        fail("unsupported v0.3 artifact plan schema")
    stages = plan.get("stages") or []
    ids = [int(s["id"]) for s in stages]
    if len(ids) != len(set(ids)) or ids != sorted(ids):
        fail("stage IDs must be unique and ordered")
    by_id = {int(s["id"]): s for s in stages}
    artifacts = [s["artifact"] for s in stages]
    if len(artifacts) != len(set(artifacts)):
        fail("stage artifact names must be unique")
    generated = [s for s in stages if s.get("generated_by_validator")]
    if len(generated) != 1 or int(generated[0]["id"]) != max(ids):
        fail("exactly one terminal stage must be generated by the validator")
    terminal = generated[0]
    if terminal["artifact"] != "INTEGRATION_READINESS.json" or terminal["schema"] != "na-cu001-integration-readiness-v0.3":
        fail("terminal v0.3 artifact is not registered")
    if by_id[1]["artifact"] != "BULK_V04_DOWNSTREAM_BRIDGE.json" or by_id[1]["schema"] != "na-cu001-audited-bulk-downstream-bridge-v0.1":
        fail("Stage 1 must be the audited v0.4 bridge")

    visiting: set[int] = set()
    visited: set[int] = set()
    def visit(stage_id: int) -> None:
        if stage_id in visiting:
            fail(f"artifact dependency cycle at stage {stage_id}")
        if stage_id in visited:
            return
        visiting.add(stage_id)
        for dep_raw in by_id[stage_id].get("dependencies", []):
            dep = int(dep_raw)
            if dep not in by_id:
                fail(f"stage {stage_id} has missing dependency {dep}")
            if dep >= stage_id:
                fail(f"stage {stage_id} depends on non-prior stage {dep}")
            visit(dep)
        visiting.remove(stage_id)
        visited.add(stage_id)
    for stage_id in ids:
        visit(stage_id)

    production_paths = [
        "na_cu001_ci/bulk_v04_downstream_bridge_v1.py",
        "na_cu001_ci/closure_engine_v2.py",
        "na_cu001_ci/closure_engine_v3.py",
        "na_cu001_ci/bulk_runner_v2.py",
        "na_cu001_ci/slab_runner_v2.py",
        "na_cu001_ci/slab_runner_v3.py",
    ]
    production = "\n".join(Path(p).read_text() for p in production_paths)
    for stage in stages:
        if stage.get("generated_by_validator"):
            continue
        if stage["artifact"] not in script:
            fail(f"stage artifact is not assembled by stage script: {stage['artifact']}")
        if stage["schema"] not in production:
            fail(f"stage schema is not emitted by production code: {stage['schema']}")

    forbidden_inputs = {terminal["artifact"], terminal["schema"]}
    for stage in stages[:-1]:
        payload = json.dumps(stage, sort_keys=True)
        if any(item in payload for item in forbidden_inputs):
            fail("terminal integration artifact appears upstream")
    for item in plan.get("required_nonresult_files") or []:
        path = item.get("path") if isinstance(item, dict) else item
        if path == terminal["artifact"]:
            fail("terminal integration artifact cannot be a required input")

    required_v04_nonresults = {
        "BULK_HANDOFF.json",
        "BULK_CONVERGENCE_RESULT.json",
        "bulk_extension_protocol_v0.1.json",
        "UPSTREAM_BULK_ARTIFACTS.json",
        "COMPUTATIONAL_CHECKPOINT_LEDGER.md",
        "REPRODUCIBILITY_GUIDE_CHECKPOINT_INSERT_v1.2.tex",
    }
    actual_nonresults = {item.get("path") if isinstance(item, dict) else item for item in plan.get("required_nonresult_files") or []}
    if not required_v04_nonresults.issubset(actual_nonresults):
        fail("required v0.4 bulk/checkpoint non-result evidence is incomplete")

    validator_call = "validate_integration_chain_v3.py"
    if validator_call not in script or "--out closure/INTEGRATION_READINESS.json" not in script:
        fail("stage script does not generate the terminal v0.3 verdict")
    if script.index(validator_call) > script.index("manifest --root closure"):
        fail("integration verdict must precede the optional closure manifest")
    if "BULK_V04_DOWNSTREAM_BRIDGE.json" not in script:
        fail("stage script does not package the audited v0.4 bridge")
    if "UPSTREAM_BULK_ARTIFACTS.json" not in script:
        fail("stage script does not package upstream bulk artifact digests")

    print(f"PASS: v0.3 artifact contract verified ({len(stages)} stages, no self-reference)")


if __name__ == "__main__":
    main()
