#!/usr/bin/env python3
"""Static anti-circularity checks for the Na/Cu(001) artifact plan and stage script."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def fail(message: str) -> None:
    raise SystemExit(f"HOLD: {message}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", required=True)
    parser.add_argument("--stage-script", required=True)
    args = parser.parse_args()
    plan_path = Path(args.plan); script_path = Path(args.stage_script)
    plan = json.loads(plan_path.read_text()); script = script_path.read_text()
    if plan.get("schema") != "na-cu001-integration-closure-v0.2":
        fail("unsupported artifact plan schema")
    stages = plan.get("stages") or []
    ids = [int(s["id"]) for s in stages]
    if len(ids) != len(set(ids)) or ids != sorted(ids):
        fail("stage IDs must be unique and ordered")
    by_id = {int(s["id"]): s for s in stages}
    artifacts = [s["artifact"] for s in stages]
    if len(artifacts) != len(set(artifacts)):
        fail("stage artifact names must be unique")
    generated = [s for s in stages if s.get("generated_by_validator")]
    if len(generated) != 1 or int(generated[0]["id"]) != max(ids):
        fail("exactly one terminal stage must be generated by the validator")
    terminal = generated[0]
    if terminal["artifact"] != "INTEGRATION_READINESS.json":
        fail("terminal generated artifact name is not registered")

    visiting: set[int] = set(); visited: set[int] = set()
    def visit(stage_id: int) -> None:
        if stage_id in visiting:
            fail(f"artifact dependency cycle at stage {stage_id}")
        if stage_id in visited:
            return
        visiting.add(stage_id)
        for dep in by_id[stage_id].get("dependencies", []):
            dep = int(dep)
            if dep not in by_id:
                fail(f"stage {stage_id} has missing dependency {dep}")
            if dep >= stage_id:
                fail(f"stage {stage_id} depends on non-prior stage {dep}")
            visit(dep)
        visiting.remove(stage_id); visited.add(stage_id)
    for stage_id in ids:
        visit(stage_id)

    for stage in stages:
        if stage.get("generated_by_validator"):
            continue
        if stage["artifact"] not in script:
            fail(f"stage artifact is not assembled by stage script: {stage['artifact']}")
        if stage["schema"] not in (Path('na_cu001_ci/closure_engine_v2.py').read_text() +
                                   Path('na_cu001_ci/bulk_runner_v2.py').read_text() +
                                   Path('na_cu001_ci/slab_runner_v2.py').read_text()):
            fail(f"stage schema is not emitted by production code: {stage['schema']}")

    forbidden_inputs = {terminal["artifact"], terminal["schema"]}
    for stage in stages[:-1]:
        payload = json.dumps(stage, sort_keys=True)
        if any(item in payload for item in forbidden_inputs):
            fail("terminal integration artifact appears in an upstream stage")
    for item in plan.get("required_nonresult_files") or []:
        path = item.get("path") if isinstance(item, dict) else item
        if path == terminal["artifact"]:
            fail("terminal integration artifact cannot be a required input")

    validator_call = "validate_integration_chain_v2.py"
    if validator_call not in script or "--out closure/INTEGRATION_READINESS.json" not in script:
        fail("stage script does not generate the terminal verdict through the validator")
    if script.index(validator_call) > script.index('manifest --root closure'):
        fail("integration verdict must precede the optional closure manifest")

    print(f"PASS: artifact contract verified ({len(stages)} stages, no self-reference)")


if __name__ == "__main__":
    main()
