#!/usr/bin/env python3
"""Build the prospective 20-job v0.4-aware Na/Cu(001) workflow.

The generated bytes are linted and hashed before the workflow is installed.
Installation under .github/workflows is intentionally deferred until an audited
v0.4 bulk PASS exists, so generation and review cannot launch surface work.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

WORKFLOW_NAME = ".github/workflows/na-cu001-computational-route-v3.yml"
STAGE = "bash na_cu001_ci/run_computational_stage_v3.sh"
PREFIX = "na-cu001-v3-"


def checkout() -> dict[str, Any]:
    return {"uses": "actions/checkout@v4"}


def download(name: str, path: str) -> dict[str, Any]:
    return {"uses": "actions/download-artifact@v4", "with": {"name": name, "path": path}}


def download_pattern(pattern: str, path: str, merge: bool = True) -> dict[str, Any]:
    return {"uses": "actions/download-artifact@v4", "with": {"pattern": pattern, "path": path, "merge-multiple": merge}}


def upload(name: str, path: str, days: int = 90, always: bool = False, required: bool = False) -> dict[str, Any]:
    step: dict[str, Any] = {"uses": "actions/upload-artifact@v4", "with": {"name": name, "path": path, "retention-days": days}}
    if always:
        step["if"] = "always()"
    if required:
        step["with"]["if-no-files-found"] = "error"
    return step


def job(needs: Any = None, timeout: int | None = None, strategy: dict[str, Any] | None = None, steps: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    value: dict[str, Any] = {"runs-on": "ubuntu-24.04"}
    if needs is not None:
        value["needs"] = needs
    if timeout:
        value["timeout-minutes"] = timeout
    if strategy:
        value["strategy"] = strategy
    value["steps"] = steps or []
    return value


def build() -> dict[str, Any]:
    paths = [
        "na_cu001_ci/bulk_extension_protocol_v0.1.json",
        "na_cu001_ci/bulk_v04_downstream_bridge_v1.py",
        "na_cu001_ci/test_bulk_v04_downstream_bridge_v1.py",
        "na_cu001_ci/slab_runner_v2.py",
        "na_cu001_ci/slab_runner_v3.py",
        "na_cu001_ci/closure_engine_v2.py",
        "na_cu001_ci/closure_engine_v3.py",
        "na_cu001_ci/test_v04_surface_entrypoints_v1.py",
        "na_cu001_ci/na_pseudo_probe_v2.py",
        "na_cu001_ci/test_closure_engine_v2.py",
        "na_cu001_ci/test_negative_gates_v2.py",
        "na_cu001_ci/validate_integration_chain_v2.py",
        "na_cu001_ci/validate_integration_chain_v3.py",
        "na_cu001_ci/workflow_contract_linter_v3.py",
        "na_cu001_ci/artifact_contract_linter_v3.py",
        "na_cu001_ci/tier_linter_v2.py",
        "na_cu001_ci/method_protocol_v0.2.json",
        "na_cu001_ci/validation_selection_protocol_v0.1.json",
        "na_cu001_ci/downstream_protocol_v0.2.json",
        "na_cu001_ci/slab_protocol_v0.3.json",
        "na_cu001_ci/integration_closure_plan_v0.3.json",
        "na_cu001_ci/run_computational_stage_v3.sh",
        "na_cu001_ci/build_v3_workflow.py",
        WORKFLOW_NAME,
    ]
    data: dict[str, Any] = {
        "name": "Na Cu001 audited v0.4 computational closure route",
        "on": {
            "workflow_dispatch": {"inputs": {"bulk_extension_run_id": {"description": "Successful audited v0.4 bulk extension run ID", "required": True, "default": "30843005718"}}},
            "push": {"branches": ["agent/na-cu001-integration"], "paths": paths},
        },
        "permissions": {"contents": "read", "actions": "read"},
        "concurrency": {"group": "na-cu001-v04-route-${{ github.sha }}", "cancel-in-progress": False},
        "env": {"BULK_EXTENSION_RUN_ID": "${{ inputs.bulk_extension_run_id || '30843005718' }}", "OMP_NUM_THREADS": "1"},
        "jobs": {},
    }
    jobs = data["jobs"]
    jobs["prepare"] = job(timeout=360, steps=[
        checkout(),
        {"name": "Audited v0.4 bulk bridge, pinned engines, Na reference, and full negative suite", "env": {"GH_TOKEN": "${{ github.token }}"}, "run": f"{STAGE} prepare"},
        upload(PREFIX + "qe", "qe_bundle", 30, required=True),
        upload(PREFIX + "base", "base", 90, required=True),
        upload(PREFIX + "raw-prepare", "base/na_reference_raw", 30, required=True),
    ])
    slab_include = [{"layers": layers, "vacuum": vacuum, "tag": f"l{layers}_v{vacuum}"} for layers in (5, 7, 9, 11) for vacuum in (12, 16, 20, 24)]
    jobs["slab-cases"] = job("prepare", 240, {"fail-fast": False, "max-parallel": 8, "matrix": {"include": slab_include}}, [
        checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"),
        {"run": f"{STAGE} slab-case '${{{{ matrix.layers }}}}' '${{{{ matrix.vacuum }}}}' '${{{{ matrix.tag }}}}'"},
        upload(PREFIX + "raw-slab-${{ matrix.tag }}", "slab_outputs", 30, True, True),
    ])
    jobs["slab-gate"] = job(["prepare", "slab-cases"], steps=[checkout(), download(PREFIX + "base", "base"), download_pattern(PREFIX + "raw-slab-*", "slab_outputs"), {"run": f"{STAGE} slab-analyze"}, upload(PREFIX + "stage2", "stage2", required=True)])
    jobs["parity"] = job(["prepare", "slab-gate"], 180, steps=[checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "stage2", "stage2"), {"run": f"{STAGE} parity"}, upload(PREFIX + "stage3", "stage3"), upload(PREFIX + "raw-parity", "stage3_raw", 30)])
    jobs["clean"] = job(["prepare", "slab-gate", "parity"], 240, steps=[checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "stage2", "stage2"), download(PREFIX + "stage3", "stage3"), {"run": f"{STAGE} clean"}, upload(PREFIX + "stage4", "stage4"), upload(PREFIX + "raw-clean", "stage4_raw", 30)])
    jobs["adsorption-cases"] = job(["prepare", "parity", "clean"], 360, {"fail-fast": False, "max-parallel": 12, "matrix": {"mobility": ["primary", "expanded"], "site": ["hollow", "bridge", "top"], "height": [2.0, 2.5, 3.0]}}, [
        checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "stage3", "stage3"), download(PREFIX + "stage4", "stage4"),
        {"run": f"{STAGE} adsorption-case '${{{{ matrix.mobility }}}}' '${{{{ matrix.site }}}}' '${{{{ matrix.height }}}}' '${{{{ matrix.mobility }}}}_${{{{ matrix.site }}}}_${{{{ matrix.height }}}}'"},
        upload(PREFIX + "raw-ads-${{ matrix.mobility }}-${{ matrix.site }}-${{ matrix.height }}", "ads_records", 30, True, True),
    ])
    jobs["adsorption-gate"] = job("adsorption-cases", steps=[checkout(), download_pattern(PREFIX + "raw-ads-*", "ads_records"), {"run": f"{STAGE} adsorption-analyze"}, upload(PREFIX + "stage6", "stage6")])
    jobs["endpoints"] = job(["prepare", "adsorption-gate"], 360, {"fail-fast": False, "matrix": {"mobility": ["primary", "expanded"]}}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "stage6", "stage6"), {"run": f"{STAGE} endpoints '${{{{ matrix.mobility }}}}'"}, upload(PREFIX + "endpoints-${{ matrix.mobility }}", "stage7_${{ matrix.mobility }}"), upload(PREFIX + "raw-endpoints-${{ matrix.mobility }}", "stage7_raw_${{ matrix.mobility }}", 30)])
    jobs["neb-cases"] = job(["prepare", "endpoints"], 360, {"fail-fast": False, "matrix": {"mobility": ["primary", "expanded"], "images": [5, 7, 9]}}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "endpoints-${{ matrix.mobility }}", "stage7_${{ matrix.mobility }}"), {"run": f"{STAGE} neb-case '${{{{ matrix.mobility }}}}' '${{{{ matrix.images }}}}'"}, upload(PREFIX + "raw-neb-${{ matrix.mobility }}-${{ matrix.images }}", "neb_records", 30, True, True)])
    jobs["neb-gates"] = job("neb-cases", strategy={"matrix": {"mobility": ["primary", "expanded"]}}, steps=[checkout(), download_pattern(PREFIX + "raw-neb-${{ matrix.mobility }}-*", "neb_records"), {"run": f"{STAGE} neb-analyze '${{{{ matrix.mobility }}}}'"}, upload(PREFIX + "path-${{ matrix.mobility }}", "stage9_${{ matrix.mobility }}")])
    jobs["ci-neb"] = job(["prepare", "endpoints", "neb-gates"], 360, {"fail-fast": False, "matrix": {"mobility": ["primary", "expanded"]}}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "endpoints-${{ matrix.mobility }}", "stage7_${{ matrix.mobility }}"), download(PREFIX + "path-${{ matrix.mobility }}", "stage9_${{ matrix.mobility }}"), {"run": f"{STAGE} ci '${{{{ matrix.mobility }}}}'"}, upload(PREFIX + "ci-${{ matrix.mobility }}", "stage11_${{ matrix.mobility }}"), upload(PREFIX + "raw-ci-${{ matrix.mobility }}", "stage11_raw_${{ matrix.mobility }}", 30)])
    jobs["mobility-gate"] = job(["endpoints", "neb-gates", "ci-neb"], steps=[checkout(), download(PREFIX + "endpoints-primary", "stage7_primary"), download(PREFIX + "endpoints-expanded", "stage7_expanded"), download(PREFIX + "path-primary", "stage9_primary"), download(PREFIX + "path-expanded", "stage9_expanded"), download(PREFIX + "ci-primary", "stage11_primary"), download(PREFIX + "ci-expanded", "stage11_expanded"), {"run": f"{STAGE} mobility-gate"}, upload(PREFIX + "stage13", "stage13")])
    jobs["hessian-plan"] = job(["mobility-gate", "endpoints", "ci-neb"], steps=[checkout(), download(PREFIX + "stage13", "stage13"), download(PREFIX + "endpoints-primary", "stage7_primary"), download(PREFIX + "endpoints-expanded", "stage7_expanded"), download(PREFIX + "ci-primary", "stage11_primary"), download(PREFIX + "ci-expanded", "stage11_expanded"), {"run": f"{STAGE} hessian-plan"}, upload(PREFIX + "hessian-plan", "stage14")])
    jobs["hessian-centers"] = job(["prepare", "hessian-plan"], 180, {"matrix": {"center": ["minimum", "saddle"]}}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "hessian-plan", "stage14"), {"run": f"{STAGE} hessian-center '${{{{ matrix.center }}}}'"}, upload(PREFIX + "hessian-center-${{ matrix.center }}", "hessian_centers", 30, True, True)])
    hessian_matrix = {"center": ["minimum", "saddle"], "region": ["na_only", "na_plus_4cu", "na_plus_8cu"], "delta": [0.02, 0.04], "slot": [0, 1, 2, 3, 4, 5, 6, 7, 8]}
    jobs["hessian-cases"] = job(["prepare", "hessian-plan"], 360, {"fail-fast": False, "max-parallel": 18, "matrix": hessian_matrix}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "hessian-plan", "stage14"), {"run": f"{STAGE} hessian-case '${{{{ matrix.center }}}}' '${{{{ matrix.region }}}}' '${{{{ matrix.delta }}}}' '${{{{ matrix.slot }}}}'"}, upload(PREFIX + "raw-hessian-${{ matrix.center }}-${{ matrix.region }}-${{ matrix.delta }}-${{ matrix.slot }}", "hessian_records", 30, True, True)])
    jobs["hessian-gate"] = job(["hessian-plan", "hessian-centers", "hessian-cases"], steps=[checkout(), download(PREFIX + "hessian-plan", "stage14"), download(PREFIX + "stage13", "stage13"), download_pattern(PREFIX + "hessian-center-*", "hessian_centers"), download_pattern(PREFIX + "raw-hessian-*", "hessian_records"), {"run": f"{STAGE} hessian-analyze"}, upload(PREFIX + "stage14-final", "stage14_final")])
    jobs["connectivity"] = job(["prepare", "endpoints", "ci-neb", "hessian-plan", "hessian-gate"], 360, steps=[checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "endpoints-primary", "stage7_primary"), download(PREFIX + "ci-primary", "stage11_primary"), download(PREFIX + "hessian-plan", "stage14"), download(PREFIX + "stage14-final", "stage14_final"), {"run": f"{STAGE} connectivity"}, upload(PREFIX + "stage15", "stage15"), upload(PREFIX + "raw-connectivity", "stage15_raw", 30)])
    jobs["sensitivity-cases"] = job(["prepare", "endpoints", "ci-neb"], 240, {"fail-fast": False, "matrix": {"variant": ["primary", "higher_cutoff", "higher_rho", "denser_kmesh", "larger_vacuum"]}}, [checkout(), download(PREFIX + "qe", "qe_bundle"), download(PREFIX + "base", "base"), download(PREFIX + "endpoints-primary", "stage7_primary"), download(PREFIX + "ci-primary", "stage11_primary"), {"run": f"{STAGE} sensitivity-case '${{{{ matrix.variant }}}}'"}, upload(PREFIX + "raw-sensitivity-${{ matrix.variant }}", "sensitivity_records", 30, True, True)])
    jobs["sensitivity-gate"] = job(["mobility-gate", "neb-gates", "ci-neb", "sensitivity-cases"], steps=[checkout(), download(PREFIX + "stage13", "stage13"), download(PREFIX + "path-primary", "stage9_primary"), download(PREFIX + "ci-primary", "stage11_primary"), download_pattern(PREFIX + "raw-sensitivity-*", "sensitivity_records"), {"run": f"{STAGE} sensitivity-analyze"}, upload(PREFIX + "stage16", "stage16")])
    final_steps = [checkout(), download(PREFIX + "base", "base"), download(PREFIX + "stage2", "stage2"), download(PREFIX + "stage3", "stage3"), download(PREFIX + "stage4", "stage4"), download(PREFIX + "stage6", "stage6"), download(PREFIX + "endpoints-primary", "stage7_primary"), download(PREFIX + "endpoints-expanded", "stage7_expanded"), download(PREFIX + "path-primary", "stage9_primary"), download(PREFIX + "path-expanded", "stage9_expanded"), download(PREFIX + "ci-primary", "stage11_primary"), download(PREFIX + "ci-expanded", "stage11_expanded"), download(PREFIX + "stage13", "stage13"), download(PREFIX + "hessian-plan", "stage14"), download(PREFIX + "stage14-final", "stage14_final"), download(PREFIX + "stage15", "stage15"), download(PREFIX + "stage16", "stage16"), download_pattern(PREFIX + "raw-*", "raw", False), {"run": f"{STAGE} finalize"}, upload(PREFIX + "closure", "closure", 90, required=True), upload(PREFIX + "raw-complete", "raw", 30, required=True)]
    jobs["finalize"] = job(["prepare", "slab-gate", "parity", "clean", "adsorption-gate", "endpoints", "neb-gates", "ci-neb", "mobility-gate", "hessian-plan", "hessian-gate", "connectivity", "sensitivity-gate"], 360, steps=final_steps)
    if len(jobs) != 20:
        raise SystemExit(f"HOLD: expected 20 jobs, built {len(jobs)}")
    return data


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(build(), separators=(",", ":")) + "\n")
    print(out)


if __name__ == "__main__":
    main()
